campus:
    resource: "@CampusBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

tienda:
    resource: "@TiendaBundle/Controller/"
    type:     annotation
    